export default [ 
    {key: 'EP', hash: 'evropske-volby', name: 'Evropské volby', about: 'Jednou za 5 let se v celé Evropské Unii konají volby do Evropského parlamentu. Česká republika volí 21 poslanců a celá je jedním obvodem. Do evropského parlamentu se dostane každá strana, hnutí nebo koalice, která přesáhne hranici 5 %, na rozdíl od sněmovních voleb zde nedochází k penalizaci koalic. Mandát získávají jednotliví kandidáti, pokud se ho vzdají, získává ho další v pořadí na kandidátce.'},
    {key: 'KV', hash: 'komunalni-volby', name: 'Komunální volby', about: 'Ve více jak 6 000 obcích, městech i městských částech probíhají jednou za 4 roky komunální volby. Ve vybraných městech jsou zároveň i volby magistrátní/primátorské, například v Praze, Brně nebo Ostravě. Počet volených zastupitelů je závislý na počtu obyvatel daného volebního obvodu, může být od jednotek až po 65 zastupitelů. Do zastupitelstva se dostane každá strana, hnutí nebo koalice, která přesáhne hranici 5 %, na rozdíl od sněmovních voleb zde nedochází k penalizaci koalic. Mandát zastupitele získávají jednotliví kandidáti, pokud se ho vzdají, získává ho další v pořadí na kandidátce. Volební průkaz platí pouze na území ČR a odevzdaný hlas pak patří k vybranému městu/obci, nelze volit ze zahraničí.'},
    {key: 'KZ', hash: 'krajske-volby', name: 'Krajské volby', about: 'Volby do krajských zastupitelstev se konají každé 4 roky a probíhají ve 13 krajích s výjimkou hlavního města Prahy. Podle velikosti kraje se volí 45, 55 nebo 65 zastupitelů. Do zastupitelstva se dostane každá strana, hnutí nebo koalice, která přesáhne hranici 5 %, na rozdíl od sněmovních voleb zde nedochází k penalizaci koalic. Mandát zastupitele získávají jednotliví kandidáti, pokud se ho vzdají, získává ho další v pořadí na kandidátce. Na volební průkaz lze volit jen v rámci kraje, volby ze zahraničí nejsou možné.'},
    {key: 'PREZ', hash: 'prezidentske-volby', name: 'Prezidentské volby', about: 'Lidé svého prezidenta vybírají od roku 2013. Celá republika je považována jako jeden volební okrsek, přičemž je možná i volba na voličský průkaz a na ambasádách v zahraničí. Prezidenta volíme většinovým systémem na 5 let, k vítězství je potřeba alespoň 50 % hlasů: pokud ani jeden kandidát nedosáhne 50 %, koná se druhé kolo, kam postupují dva nejsilnější kandidáti.'},
    {key: 'PS', hash: 'snemovni-volby', name: 'Sněmovní volby', about: 'Sněmovnu tvoří 200 poslanců, které volíme na dobu 4 let. Volí se poměrným způsobem s využitím Imperialiho metody s výpočtem mandátů podle volebních obvodů, které tvoří kraje. Dříve se používala d\'Hondtova metoda. Strany, hnutí a koalice musí dosáhnout alespoň na 5 % (koalice podle počtu stran), aby získali poslanecké mandáty. Mandát získává konkrétní poslanec. Pokud se vzdá mandátu, získává ho další v pořadí na kandidátce. Pokud poslanec změní stranu či klub, mandát mu zůstává. Sněmovna si může odhlasovat předčasné rozpuštění, což vede k vypsání nových voleb. Volit je možné na voličský průkaz i ze zahraničí, výsledky se započítávají losem do jednoho z krajů. Je možné používat preferenční hlasování, volič má k dispozici jeden hlas.'},
    {key: 'SENAT', hash: 'senatni-volby', name: 'Senátní volby', about: 'Senát tvoří 81 senátorů, kteří jsou voleni na 6 let. Každé dva roky se volí třetina nových senátorů, vždy v 27 obvodech z 81 obvodů celkem. Senátoři se volí většinovým systémem, ke zvolení je potřeba zisku alespoň 50 % hlasů v daném obvodě: pokud ani jeden kandidát nedosáhne 50 %, koná se druhé kolo, kam postupují dva nejsilnější kandidáti. V případě, že mandát senátora skončí předčasně, konají se doplňkové volby. Senátor, který získá mandát, ho získává jen do dalších řádných senátních voleb v daném obvodě. Voličský průkaz lze uplatnit pouze v rámci obvodu, volby ze zahraničí nejsou možné.'},
    {key: 'REFER', hash: 'referendum', name: 'Referendum', icon: 'evropske-volby', about: 'Všelidové hlasování se zatím konalo pouze jednou.'}
];
